version: "3.9"
services:
  proxysql:
    ports:
      - "16032:6032"
      - "16033:6033"
      - "16070:6070"
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf
    image: proxysql/proxysql
    depends_on:
      - "mysql_node0"
      - "mysql_node1"
  mysql_node0:
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: shared
      MYSQL_USER: app
      MYSQL_PASSWORD: foobar
    image: mysql:5.7
    volumes:
      - ./data/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./data/02-seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
  mysql_node1:
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: acmeinc
      MYSQL_USER: app
      MYSQL_PASSWORD: foobar
    image: mysql:5.7
    volumes:
      - ./data/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./data/03-acme.sql:/docker-entrypoint-initdb.d/03-acme.sql