version: "3.9"
services:
  proxysql:
    ports:
      - "16032:6032"
      - "16033:6033"
      - "16070:6070"
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf
    image: proxysql/proxysql
    depends_on:
      - "mysql_node0"
      - "mysql_node1"
  mysql_node0:
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: shared
      MYSQL_USER: app
      MYSQL_PASSWORD: foobar
    image: mysql:5.7
    volumes:
      - ../data:/docker-entrypoint-initdb.d
  mysql_node1:
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: superdupergames
      MYSQL_USER: app
      MYSQL_PASSWORD: foobar
    image: mysql:5.7
    volumes:
      - ../data:/docker-entrypoint-initdb.d